export function isHeaders(it: any): boolean;
export function isRequest(it: any): it is Request;
export function isResponse(it: any): it is Response;
export function toHeaders(it: any): any;
export { default as httpMethods } from "./http-methods.js";
export * from "./http-methods.js";
export * from "./http-codes.js";
export * as httpCodes from "./http-codes.js";
export * as mimeTypes from "./mime-types.js";
import { Request } from './api.native.js';
import { Response } from './api.native.js';
